name: Test Action

on: 
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f1000879@ds.study.iitm.ac.in
        run: echo "Hello, world!"
